kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: ne-crosschain-staging
spec:
    clusterIP: None
    ports:
    -   port: 27017
    selector:
        app: mongodb

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongodb-node
    namespace: ne-crosschain-staging
spec:
  serviceName: mongodb
  selector:
    matchLabels:
        app: mongodb
  replicas: 1
  template:
    metadata:
        labels:
            app: mongodb
    spec:
        containers:
        -   name: mongodb-node
            image: mongo:3.6
            command: [ "/usr/bin/mongod", "--smallfiles", "--bind_ip_all" ]
            volumeMounts:
            -   mountPath: "/data/db"
                name: mongo-data
            ports:
            -   containerPort: 27017
       
        
  volumeClaimTemplates:
  - metadata:
        name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ne-crosschain-staging-ingress
  namespace: ne-crosschain-staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
    - hosts:
      - ne-crosschain.staging.newearthart.tech
      secretName: ne-crosschain-staging-tls

  rules:
  - host: ne-crosschain.staging.newearthart.tech
    http:
      paths:
      - path: /
        backend:
          serviceName: ne-server 
          servicePort: 3300                    


---


apiVersion: v1
kind: Service
metadata:
  name: ne-server
  namespace: ne-crosschain-staging
  labels:
    app: ne-server
spec:
  ports:
  - port: 3300
  selector:
    app: ne-server


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ne-server
  namespace: ne-crosschain-staging
  labels:
    app: ne-server
spec:
  selector:
    matchLabels:
        app: ne-server
 
  template:
    metadata:
        labels:
            app: ne-server
    spec:
        containers:
        -   image: cloudconnect.scanrev.com:5000/ne-crosschain-loan:1.0.7
            name: ne-server
            ports:
            - containerPort: 3300

        imagePullSecrets:
        - name: secret-cloudconnect


